# Generated by Kavia CodeGen

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('tags', models.TextField(blank=True, db_index=True, default='', help_text="Comma-separated tags string. e.g. 'alpha,beta,gamma'")),
                ('confidence', models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ['-updated_at', '-priority', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('osint', 'OSINT'), ('sigint', 'SIGINT'), ('humint', 'HUMINT'), ('other', 'Other')], db_index=True, max_length=10)),
                ('url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('keyword', 'Keyword'), ('pattern', 'Pattern'), ('feature', 'Feature')], db_index=True, max_length=10)),
                ('value', models.TextField(db_index=True)),
                ('score', models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.source')),
            ],
            options={
                'ordering': ['-created_at', '-score'],
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rationale', models.TextField(blank=True, default='')),
                ('analyst_notes', models.TextField(blank=True, default='')),
                ('weight', models.FloatField(db_index=True, default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='api.indicator')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='api.target')),
            ],
            options={
                'ordering': ['-created_at', '-weight'],
                'unique_together': {('target', 'indicator')},
            },
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['status', 'priority'], name='api_target_status__9fa8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['confidence'], name='api_target_confide_46fad1_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['updated_at'], name='api_target_updated__6ff691_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['type'], name='api_source_type_c87cda_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['name'], name='api_source_name_712d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['type'], name='api_indicat_type_b638a3_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['score'], name='api_indicat_score_5bcf02_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['created_at'], name='api_indicat_created__a74ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['target', 'indicator'], name='api_associa_target__0c58b2_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['target', 'weight'], name='api_associa_target__e152e5_idx'),
        ),
    ]
