# Generated by Django 5.2 on 2025-11-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='association',
            new_name='api_associa_target__4e5f12_idx',
            old_name='api_associa_target__0c58b2_idx',
        ),
        migrations.RenameIndex(
            model_name='association',
            new_name='api_associa_target__b1da5d_idx',
            old_name='api_associa_target__e152e5_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='api_indicat_type_f7fc3b_idx',
            old_name='api_indicat_type_b638a3_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='api_indicat_score_9ee8a3_idx',
            old_name='api_indicat_score_5bcf02_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='api_indicat_created_09b090_idx',
            old_name='api_indicat_created__a74ee0_idx',
        ),
        migrations.RenameIndex(
            model_name='source',
            new_name='api_source_type_6828ff_idx',
            old_name='api_source_type_c87cda_idx',
        ),
        migrations.RenameIndex(
            model_name='source',
            new_name='api_source_name_0150b0_idx',
            old_name='api_source_name_712d7b_idx',
        ),
        migrations.RenameIndex(
            model_name='target',
            new_name='api_target_status_ac21b0_idx',
            old_name='api_target_status__9fa8a6_idx',
        ),
        migrations.RenameIndex(
            model_name='target',
            new_name='api_target_confide_a0d6be_idx',
            old_name='api_target_confide_46fad1_idx',
        ),
        migrations.RenameIndex(
            model_name='target',
            new_name='api_target_updated_e009ea_idx',
            old_name='api_target_updated__6ff691_idx',
        ),
    ]
